### DISCUSSION TITLE
Problem with `ez.dateOut()` in workspace environment

### DISCUSSION THREAD

**Discussion by JonathanCabezas** [RobinTail/express-zod-api#2024] [Q&A] [answered]
I have a file containing:
```ts
export const productPriceSchema = z
  .object({
    price: z.number(),
    date: ez.dateOut(),
  })
```

I have the following endpoint importing the schema:

```ts
export const getProductPricesEndpoint = routeFactory
  .addMiddleware(authMiddleware(Permission.Read, Modules.Product))
  .build({
    method: "get",
    tag: "product",
    description: "Get all the product prices.",
    input: emptySchema,
    output: z.object({ items: z.array(productPriceSchema) }),
    handler: async () => {
      const items = await getProductPrices();

      return { items };
    },
  });
```

I get the following error:
```
DocumentationError: Using z.date() within output schema is forbidden. Please use ez.dateOut() instead. Check out the documentation for details.
Caused by response schema of an Endpoint assigned to GET method of /api/product/unit/prices path.
```

If I inline the schema instead of importing it, it works fine.

I don't think this is related, but the import is done from another package (I have a monorepo structure).

I already had this issue before, and it disappeared I don't know why.

I tried with `Bun` and `tsx` runtimes, getting the same error.

**Comment by RobinTail** [comment]
What are the versions of 
- `express-zod-api`
- `typescript`
-  and `Node`

 @JonathanCabezas ?

**Reply by JonathanCabezas** [reply]
From `pnpm-lock.yaml`:
```
apps/back:
    dependencies:
      body-parser:
        specifier: ^1.20.2
        version: 1.20.2
      express:
        specifier: ^4.18.2
        version: 4.19.2
      express-zod-api:
        specifier: ^20.7.1
        version: 20.7.1(@types/express@4.17.21)(@types/http-errors@2.0.4)(compression@1.7.4)(express@4.19.2)(http-errors@2.0.0)(typescript@5.2.2)(zod@3.23.8)
      zod:
        specifier: ^3.22.4
        version: 3.23.8
    devDependencies:
      '@types/node':
        specifier: ^20.5.2
        version: 20.14.10

packages/shared:
    dependencies:
      express-zod-api:
        specifier: ^20.7.1
        version: 20.7.1(@types/express@4.17.21)(@types/http-errors@2.0.4)(compression@1.7.4)(express@4.19.2)(http-errors@2.0.0)(typescript@5.4.5)(zod@3.23.8)

      zod:
        specifier: ^3.22.4
        version: 3.23.8
    devDependencies:
      '@types/node':
        specifier: ^20.5.2
        version: 20.14.10
```

I do notice there's a difference of typescript version betweek my backend and my shared package, could this be the reason ?

There is no `Node` version, I tried with:

- Bun@1.1.21
- tsx@4.19.0

I didn't copy everything, do you need more information ?

**Reply by RobinTail** [reply]
@JonathanCabezas , `express-zod-api` was never tested on `bun`.
It might be an issue of `bun`.

**Reply by RobinTail** [reply]
Also, please try upgrading `bun`.
It's `1.1.27` now, @JonathanCabezas

**Reply by RobinTail** [reply]
- You are using `date: ez.dateOut()`;
- but you're getting error: `Using z.date() is forbidden`;
- `ez.dateOut()` does utilize `z.date()` within;
- but it should not get there because `ez.dateOut()` is also a branded schema, having its own dedicated depicter, not the depicter of `z.date()`;

the fact that it still does get there means that the Zod Plugin that `express-zod-api` injects is not executed, failed or being tree-shaken somehow by your runtime, which is `bun`, @JonathanCabezas , so that the feature of runtime distinguishable brands is not working.

I made a test for your code, demonstrating that it works well in every supported Node version:
https://github.com/RobinTail/express-zod-api/pull/2025

But it's not yet clear regarding `bun`. I have a suspicion I need to prove, @JonathanCabezas

**Reply by JonathanCabezas** [reply]
Upgrading `bun` did not fix it.
Also I had the same problem with `tsx`.
I can't try with `Node` right now as my project does not fully comply to ESM standards and does not start with `Node`.

Thank you for you answer, I will keep digging.

**Reply by RobinTail** [reply]
Yeah, you know, it's strange, because I also managed to run it using `bun`:

https://github.com/RobinTail/express-zod-api/actions/runs/10759041666/job/29835239011

Exact same versions. And it works without any issues, @JonathanCabezas 
Perhaps the issues is something else.

**Reply by RobinTail** [reply]
What I can tell you for sure is that this line must be executed:

https://github.com/RobinTail/express-zod-api/blob/975e37996174d5ff1a9e478bd6baec4004c043f3/src/index.ts#L1

it runs the code that makes the difference between `z.date()` and `z.dateOut()`.

Try to ensure `import "express-zod-api"` in the beginning of your entry file, @JonathanCabezas

**Reply by RobinTail** [reply]
> Also I had the same problem with tsx.

https://tsx.is/node-enhancement

![image](https://github.com/user-attachments/assets/b0df1302-120c-4259-b50a-04f666cbf807)

> There is no Node version,

, and because you don't have Node.js installed, only `bun`, I'm not sure how exactly it works in your case.

**Reply by JonathanCabezas** [reply]
> Yeah, you know, it's strange, because I also managed to run it using `bun`:
> 
> https://github.com/RobinTail/express-zod-api/actions/runs/10759041666/job/29835239011
> 
> Exact same versions. And it works without any issues, @JonathanCabezas Perhaps the issues is something else.

This is not an MVCE, and I'm really unsure what's causing this problem so it's hard to produce one...
I only shared the one endpoint causing the issue. If I replace the imported schema with an inlined version, it works but another endpoint using `ez.dateOut()` is raising the same error.

Adding `import "express-zod-api"` to the beginning of my entry file didn't fix it.

I'll try to mess around with `tsx`.

Also, it stopped working after a specific commit so I'll try to narrow it down there, but I didn't change anything related to endpoints/schemas there.

**Reply by JonathanCabezas** [reply]
`tsx` runs my globally installed `Node.js` which is `v22.0.0`, still getting the error.

**Comment by JonathanCabezas** [comment, marked as answer]
@RobinTail So this had nothing to do with `bun`.

I had indeed 2 versions of typescript between my `back` and my `packages/shared` workspace. This was causing `express-zod-api` to be bundled twice at 2 different locations by `pnpm`. I don't know exactly how, but this broke something in `express-zod-api`.

 ```
apps/back:
    dependencies:
      express-zod-api:
        specifier: ^20.7.1
        version: 20.7.1(@types/express@4.17.21)(@types/http-errors@2.0.4)(compression@1.7.4)(express@4.19.2)(http-errors@2.0.0)(typescript@5.2.2)(zod@3.23.8)

packages/shared:
    dependencies:
      express-zod-api:
        specifier: ^20.7.1
        version: 20.7.1(@types/express@4.17.21)(@types/http-errors@2.0.4)(compression@1.7.4)(express@4.19.2)(http-errors@2.0.0)(typescript@5.4.5)(zod@3.23.8)
```

I fixed it by removing the typescript dependency from both projects and using a global dependency at my monorepo root.
