### DISCUSSION TITLE
Best practice for accepting numbers in query params

### DISCUSSION THREAD

**Discussion by niklashigi** [RobinTail/express-zod-api#754] [Q&A] [answered]
If I want to accept a number as a query parameter (for example, `page_size`), what's the best way to define its schema? `z.number()` doesn't seem to work (it returns an `Expected number, received string` error).

I also tried the following:

```ts
z
  .preprocess(
    value =>
      typeof value === 'string' ? Number.parseInt(value) : undefined,
    z.number().int().min(1).max(100),
  )
```

This _works_, but the generated OpenAPI schema is strange...

```
schema:
  description: The number of results to return per page
  format: int64 (preprocessed)
  minimum: 1
  exclusiveMinimum: false
  maximum: 100
  exclusiveMaximum: false
```

...and confuses code generators and documentation portals (note the `json` and the multi-line text field on the right):

<img width="645" alt="image" src="https://user-images.githubusercontent.com/29176678/208926610-83dfb0de-b559-48ff-949d-4891af8a9ac3.png">

Is there a better way to do this?
